In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
result=arr+10 # here we use brodcasting i.e numpy create array of 10 and add with original array
#[1,2,3,4,5] + [10,10,10,10,10] for that numpy donot take memory space it create internally

In [6]:
result

array([11, 12, 13, 14, 15])

In [12]:
# adding of tow array
arr1=np.array([11,3,4,56,23,90])
arr2=np.array([34,42,5,8,18,72])

In [13]:
array_sum=arr1+arr2

In [14]:
array_sum

array([ 45,  45,   9,  64,  41, 162])

In [17]:
# addition of 2D array with 1D array
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([7,8,9])
arraysum=arr1+arr2

In [18]:
arraysum

array([[ 8, 10, 12],
       [11, 13, 15]])

In [19]:
# find normalization array
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


In [20]:
mean

array([20., 30., 40.])

In [21]:
std

array([7.07106781, 7.07106781, 7.07106781])