In [1]:
import numpy as np


In [2]:
arr1=np.array([1,2,3,4])

In [4]:
arr1

array([1, 2, 3, 4])

In [6]:
arr2=np.array(([1,2,3],[4,5,6]))
print(arr2)

[[1 2 3]
 [4 5 6]]


In [11]:
# creating specific array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((5,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.arange(1,100,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [18]:
np.linspace(1,100,6)

array([  1. ,  20.8,  40.6,  60.4,  80.2, 100. ])

In [33]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [20]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [22]:
myarr.shape

(4, 3)

In [23]:
myarr.size

12

In [24]:
myarr.ndim

2

In [25]:
myarr.dtype

dtype('int32')

In [27]:
# explicit type conversion
myarr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], dtype='float32')

In [28]:
#implicit type conversion
n=myarr.astype('float64')

In [29]:
n.dtype

dtype('float64')

In [34]:
# reshape the array
reshape=myarr.reshape((3,4))

In [35]:
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [36]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])