In [4]:
import numpy as np


In [5]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [6]:
flat=arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
flat[1:4]

array([2, 3, 4])

In [9]:
flat[0]

1

In [22]:
flat

array([ 1, 30,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
b=flat[1:4]

In [12]:
b

array([2, 3, 4])

In [13]:
b[0]=30

In [14]:
b

array([30,  3,  4])

In [16]:
flat #here original array also change cause in slicing it not make copy it return view of original array

array([ 1, 30,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
#for getting copy of array we use copy method
b=flat[1:4].copy()

In [9]:
b

array([2, 3, 4])

In [23]:
flat

array([ 1, 30,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [25]:
#fancy indexing in this we pass index and we get elements of that index
flat[[1,2,3]]

array([30,  3,  4])

In [32]:
#boolean masking we pass condition and we get element which satisfy that condition 
arr=np.array([34,2,23,51,44,39])
mask=arr>25
arr[mask]

array([34, 51, 44, 39])