In [3]:
import numpy as np

In [2]:
arr=np.array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])


In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [4]:
arr[0]

array([1, 2, 3])

In [5]:
arr[1]

array([4, 5, 6])

In [7]:
np.sum(arr,axis=0)

array([23, 27, 31])

In [8]:
np.sum(arr,axis=1)

array([ 6, 15, 24, 36])

In [9]:
arr[0][1]

2

In [4]:
arr=np.array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])



In [5]:
arr[0,1]

2

In [7]:
arr[0:2,1:3] #0th and 1st row and 1st column and 2nd column out of that common element is given

array([[2, 3],
       [5, 6]])

In [16]:
arr[1:3,0:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [17]:
arr[2:4,1:3]

array([[ 8,  9],
       [12, 13]])

In [15]:
#3D array
arr3D=np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]]])

In [42]:
arr3D.shape

(2, 2, 3)

In [34]:
arr3D[1,1,2]

12

In [9]:
arr3D[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [41]:
arr3D[1,1,2]

12

In [16]:
# changing element of corresponding axis
arr3D[1,1,2]=0

In [17]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11,  0]]])