In [13]:
import numpy as np
import sys

In [2]:
arr=np.array([23,45,18,7])

In [3]:
arr

array([23, 45, 18,  7])

In [4]:
arr.dtype

dtype('int32')

In [6]:
arr.astype("float32")

array([23., 45., 18.,  7.], dtype=float32)

In [7]:
arr.astype("bool")

array([ True,  True,  True,  True])

In [10]:
arr.astype("complex64")

array([23.+0.j, 45.+0.j, 18.+0.j,  7.+0.j], dtype=complex64)

In [17]:
arr1=np.array([1,2,3],dtype="int64") # in int64 3*8byte=24
arr2=np.array([1,2,3],dtype="int32") #in int32 3*4byte=12

In [15]:
print(arr1.nbytes)

24


In [16]:
print(arr2.nbytes)

12
