In [2]:
import numpy as np

In [50]:
# 1st problem create numpyarray of random numbers
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
arr.shape

(3, 3)

In [40]:
# 2nd problem convert float array into integer
arr2=np.array([1.1,2.2,3.3])
int_arr=arr2.astype('int32')

In [41]:
int_arr

array([1, 2, 3])

In [42]:
#3rd problem use of fancy indexing to find even num
arr3=np.array([1,2,3,4,5,6,7,8])
arr3[[1,3,5,7]]

array([2, 4, 6, 8])

In [49]:
#4th problem convert 1D array into 2D
arr4=np.array([1,2,3,4,5,6,7,8,9])
arr4.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
#5th problem use of boolean mask
arr5=np.array([23,45,50,55,61,78,9,99,2,5,32])
mask=arr5>50
arr5[mask]

array([55, 61, 78, 99])

In [5]:
#6th problem extracting 3rd element 
arr=np.array([10,20,30,40,50])
arr[2]

30

In [6]:
#7th problem getting last two rows
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
arr[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [22]:
#8th reverse 1D array
arr1=np.array([10,20,30,40,50])
arr2=arr1[::-1]

In [32]:
arr2

array([50, 40, 30, 20, 10])

In [24]:
#9th performing operations on array
a=np.array([1,2,3])
b=np.array([4,5,6])

In [27]:
print(a*3)
print(b*3)

[3 6 9]
[12 15 18]


In [30]:
#10th problem sum of all elements
s=np.array([[1,2,3],[4,5,6]])
s1=s.sum()

In [31]:
s1

21

In [35]:
sk=np.zeros((2,5))

In [39]:
sk[0,4]=5

In [40]:
sk

array([[0., 0., 0., 0., 5.],
       [0., 0., 0., 0., 0.]])

In [58]:
# 11th problem creating even number array
even=np.arange(1,21)
even[even%2==0] # boolean masking is use

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [59]:
#12th problem getting middle 3x3 matrix
nparr=np.arange(1,26).reshape(5,5)

In [60]:
nparr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [61]:
nparr[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [62]:
#13th problem stack arrays vertically and horizontally
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])


In [71]:
c1=np.vstack((a,b)) # use of vstack fuction for vertical arrangment
c2=np.hstack((a,b)) # hstack function for horizontal arrangment

In [72]:
c1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
c2

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [83]:
ab=np.random.randint(0, 10, (3, 3))


In [84]:
ab

array([[4, 5, 7],
       [0, 6, 6],
       [2, 7, 8]])

In [106]:
#14th problem subtract mean from rows
new=ab.mean(axis=1,keepdims=True)

In [107]:
new_array=ab-new

In [109]:
new_array

array([[-1.33333333, -0.33333333,  1.66666667],
       [-4.        ,  2.        ,  2.        ],
       [-3.66666667,  1.33333333,  2.33333333]])

In [114]:
#15th problem boolean masking 
arr = np.array([10, 20, 30, 40, 50])
arr[arr>30]=0

In [115]:
arr

array([10, 20, 30,  0,  0])

In [121]:
#16th problem extracing even numbers form random number array
arr=np.random.randint(1,100,(4,4))

In [122]:
arr

array([[61, 11, 57, 54],
       [52,  6, 16, 20],
       [57, 59, 36, 25],
       [30,  1, 69, 85]])

In [123]:
arr[arr%2==0]

array([54, 52,  6, 16, 20, 36, 30])

In [135]:
#17th problem find row with highest sum
arr=np.random.randint(1,100,(3,3))

In [136]:
arr

array([[19,  1, 95],
       [23,  2, 97],
       [27, 48, 38]])

In [137]:
print(f"highest sum Row is:{arr.sum(axis=1).argmax()}")

highest sum Row is:1


In [156]:
#18th problem array of numbers between 0 and 1
arr=np.linspace(0,1,15)

In [157]:
arr

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [158]:
# 19th problem element which greater than mean of array
arr=np.array([12,31,32,21,11,3,76,8,90])

In [159]:
mask=np.mean(arr)
arr[arr>mask]

array([32, 76, 90])