In [2]:
#using python list
import numpy as np 
import time 

size=1_000_000
l1=list(range(size))
l2=list(range(size))
start= time.time()
sum=[(x+y) for x,y in zip(l1,l2)]
end=time.time()
print(sum[0:20])
print(end - start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]
0.11967992782592773


In [13]:
#using numpy array
import numpy as np 
import time 

size=1_000_000
l1=np.array(list(range(size)))
l2=np.array(list(range(size)))
start= time.time()
sum= l1+l2
end=time.time()
print(sum[0:20])
print(end - start)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
0.01994800567626953


In [3]:
np.array([1,2,3,4,5]) 

array([1, 2, 3, 4, 5])

In [6]:
arr=np.array([[3,4,5],[6,7,8]])

In [7]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(2, 3)

In [3]:
import sys
list_data=list(range(1000))
numpy=np.array(list_data)
print("python list size:", sys.getsizeof(list_data)*len(list_data))
print("numpy array size", numpy.nbytes)

python list size: 8056000
numpy array size 4000


In [5]:
#for updating element we have to use loop in python list
list_data=[1,2,3,4,5,]
new_list=[x*x for x in list_data]
print(new_list)

[1, 4, 9, 16, 25]


In [8]:
# In nparray vectorization is use for updation of array 
nparray=np.array([1,2,3,4,5])
npsquare=nparray*nparray
print(npsquare)

[ 1  4  9 16 25]


In [14]:
import time
# for python list 
list_data=list(range(1000))
start=time.time()
new_list=[x**2  for x in list_data]
end=time.time()
print(new_list[0:30])
print(end - start)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841]
0.0009996891021728516


In [15]:
# for numpy array
nparray=np.array(list(range(1000)))
start=time.time()
npsquare=nparray**2
end=time.time()
print(npsquare[0:30])
print(end - start)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361 400 441 484 529 576 625 676 729 784 841]
0.0


In [18]:
nparray=np.array(list(range(10,101)))
print(nparray.shape)

(91,)


In [20]:
import sys
nparray=np.array(list(range(100000)))
npsize=nparray.nbytes
print(npsize)

400000
